name: Update Ranking

on:
  pull_request:
    types: [closed]

jobs:
  update-ranking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run ranking update script
        run: python scripts/update_ranking.py

      - name: Commit updated ranking
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add RANKING.md
          git commit -m "Auto-update ranking [bot]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"